#!/bin/bash

INCLUDE_DIRECTORY="include"
BUILD_DIRECTORY="build"
CPP_FILES=$(find src -type f -name "*.cpp")


function getUserArch()
{
  USER_ARCHITECTURE=$(uname -m)

  case "$USER_ARCHITECTURE" in
    x86_64)
      USER_ARCHITECTURE="x64"
      ;;
    i386 | i486 | i586 | i686)
      USER_ARCHITECTURE="x86"
      ;;
  esac
}

function getAssemblyScripts()
{
  ASSEMBLY_FILES=$(find arch/"$USER_ARCHITECTURE" -type f -name "*.S")
}

function mountAssembly()
{
  ASSEMBLY_OBJECTS=""

  for file in $ASSEMBLY_FILES; do
    base_name=$(basename "$file")
    output_file="$build_dir/$base_name).o"

    as -o "$output_file" "$file"

    ASSEMBLY_OBJECTS="$ASSEMBLY_OBJECTS $output_file"
  done
}

function main()
{
  mkdir -p "$BUILD_DIRECTORY"
  
  getUserArch
  getAssemblyScripts
  mountAssembly
}


main
